{
  "formatVersion": "1.1",
  "component": {
    "group": "com.clearme.sdk",
    "module": "clearsdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "clearsdk-1.0.0.aar",
          "url": "clearsdk-1.0.0.aar",
          "size": 146481,
          "sha512": "e7534a814472209a895f89522ca52693e0163796c453433af2b17269a314d7eda9bfa42d2bd591571ab70ad6cc2bad5d98537df348bc51f33a4825b2a88ef064",
          "sha256": "392a757128b11d2350416aa93066c8541f6f85a5148074fb36f430836eef6b1a",
          "sha1": "781b141da7240eeeed85f763cd82609cbefb53a0",
          "md5": "b25e5c70e6aad2353412fb86230adc13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "clearsdk-1.0.0.aar",
          "url": "clearsdk-1.0.0.aar",
          "size": 146481,
          "sha512": "e7534a814472209a895f89522ca52693e0163796c453433af2b17269a314d7eda9bfa42d2bd591571ab70ad6cc2bad5d98537df348bc51f33a4825b2a88ef064",
          "sha256": "392a757128b11d2350416aa93066c8541f6f85a5148074fb36f430836eef6b1a",
          "sha1": "781b141da7240eeeed85f763cd82609cbefb53a0",
          "md5": "b25e5c70e6aad2353412fb86230adc13"
        }
      ]
    }
  ]
}
