{
  "formatVersion": "1.1",
  "component": {
    "group": "com.clearme.sdk",
    "module": "clearsdk",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "clearsdk-1.1.0.aar",
          "url": "clearsdk-1.1.0.aar",
          "size": 147193,
          "sha512": "bd33c32b4ca305ff2434f1f0e9935a1ce1604fab0ae457a304fc66d3d60dc2f65b58a93e22ff346a3a7863c0e87086b7589e4a146168e7d7fcee61c3e4737bf4",
          "sha256": "aae69c7ef8e7514169173e5345eecf8e8e857116cb8fdedcc4e97415508b7ad7",
          "sha1": "e3965cdadae6c2fa56e6a54e01409b1994efc4cb",
          "md5": "b6844c5109bd90bdf4d828617206b2bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "clearsdk-1.1.0.aar",
          "url": "clearsdk-1.1.0.aar",
          "size": 147193,
          "sha512": "bd33c32b4ca305ff2434f1f0e9935a1ce1604fab0ae457a304fc66d3d60dc2f65b58a93e22ff346a3a7863c0e87086b7589e4a146168e7d7fcee61c3e4737bf4",
          "sha256": "aae69c7ef8e7514169173e5345eecf8e8e857116cb8fdedcc4e97415508b7ad7",
          "sha1": "e3965cdadae6c2fa56e6a54e01409b1994efc4cb",
          "md5": "b6844c5109bd90bdf4d828617206b2bf"
        }
      ]
    }
  ]
}
